### ISSUE TITLE
ERROR: only_if is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by joanteixi** [francisbesset/ansible-playbooks#2]
Hi, 

when i try to execute your playbook, I get this error:
ERROR: only_if is not a legal parameter in an Ansible task or handler

I haven't find "only_if" tag in ansible doc so I'm not sure if is some tag deprecated or I'm doing something wrong.

Thanks!

Joan

**Comment by avelis** [comment]
Consider using conditionals instead http://docs.ansible.com/playbooks_conditionals.html

**Comment by anshprat** [comment]
only_if was deprecated for a while and has been remove in ansible 1.5 onwards

https://github.com/ansible/ansible/blob/devel/CHANGELOG.md
